name: Python CI/CD Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify your Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    # Step 4: Start Flask App
    - name: Start Flask App
      run: |
        python app.py &  # Run Flask app in the background
        sleep 10  # Allow some time for the server to start

    # Step 5: Check Flask App Localhost URL
    - name: Check Flask App
      run: |
        curl --silent http://127.0.0.1:5000/view || echo "Flask app is not accessible"

    # Step 6: Notify success
    - name: Notify Success
      run: echo "Pipeline executed successfully! Flask app ran on localhost."
