name: Python CI/CD Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify your Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


 # Step 4: Run Flask App and Log Output
    - name: Start Flask App
      run: |
        python app.py > flask_output.log 2>&1 &  # Run the app and log output
        sleep 10  # Allow Flask app to start
        cat flask_output.log  # Display the log for debugging

    # Step 5: Check Flask App URL
    - name: Check Flask App URL
      run: |
        curl --silent http://127.0.0.1:8080/view || echo "Flask app is not accessible"

    # Step 6: Verify Logs
    - name: Display Logs
      run: |
        if test -f LOGGING_INFO.log; then
          cat LOGGING_INFO.log
        else
          echo "LOGGING_INFO.log not found."
        fi

    # Step 7: Notify success
    - name: Notify Success
      run: echo "Pipeline executed successfully! Logs displayed above."
