name: Python CI/CD Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify your Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt



        # Step 4: Install localtunnel
    - name: Install localtunnel
      run: npm install -g localtunnel

    # Step 5: Start Flask App
    - name: Start Flask App
      run: |
        python app.py &  # Start Flask app in the background
        sleep 10         # Allow Flask server to start

    # Step 6: Expose Flask App to Public via Localtunnel
    - name: Expose Flask App
      run: |
        lt --port 8080 --subdomain flaskci > lt_url.txt &
        sleep 5  # Allow localtunnel to initialize

    # Step 7: Display Public URL
    - name: Get Public URL
      run: cat lt_url.txt
